export const EARLY_PAYMENT_DISCOUNT_RATE = 0.10;
export const EARLY_PAYMENT_DAYS_THRESHOLD = 10;
export const VOLUME_DISCOUNT_RATE = 0.05;
export const VOLUME_DISCOUNT_MIN_FINES = 3;
export const SEVERELY_OVERDUE_DAYS_THRESHOLD = 30;
